# Analyse Salmonella enterica
library(ggplot2)
library(dplyr)


# Read in S. enterica defensefinder results for ATB
# 1) Download all data from OSF ATB DefenseFinder component https://osf.io/hpgac/overview
# 2) Download species calls https://osf.io/h7wzy/files/7t9qd
# 3) Filter on species "Salmonella enterica"
atb_systems = read.csv('~/Downloads/senterica_defensefinder_results.csv',
                       header=T,
                       stringsAsFactors = F)
# Read in S. enterica defensfinder results for RefSeq systems 
# (separately generated by running DefenseFinder on complete RefSeq S. enterica genomes)
complete_systems = read.csv('Salmonella-enterica-RefSeq-systems.tsv',
                            header=T,
                            stringsAsFactors = F,
                            sep='\t')

atb_systems_prop = atb_systems %>% group_by(type) %>%
  summarise(n.ATB=length(type)) %>%
  mutate(prop.ATB=n.ATB/sum(n.ATB) * 100)
complete_systems_prop = complete_systems %>% group_by(type) %>%
  summarise(n.Refseq=length(type)) %>%
  mutate(prop.Refseq=n.Refseq/sum(n.Refseq) * 100)

systems_merged = merge(atb_systems_prop, complete_systems_prop, 
                       by="type", all=TRUE)
# Only keep those where RefSeq has some observed
systems_merged_plot = systems_merged[which(!is.na(systems_merged$prop.Refseq)),]
write.csv(systems_merged_plot, file="FigS15_raw_data.csv")
p = ggplot(systems_merged_plot, aes(prop.Refseq, prop.ATB))+
  geom_abline(slope=1, intercept =0, linetype='dashed')+
  geom_point()+
  theme_bw()+
  xlab("% of genomes (RefSeq: n=1,672)")+
  ylab("% of genomes (AllTheBacteria: n=644,699)")+
  scale_y_log10(breaks=c(0.001, 0.01, 0.1, 1, 10), labels = scales::label_number())+
  scale_x_log10(breaks=c(0.001, 0.01, 0.1, 1, 10), labels = scales::label_number())+
  coord_fixed()
ggsave(p, file='FigS15-plot-correlation-ATB-RefSeq-Salmonella-enterica.pdf', width=4, height=4)
p.labels = p+
  ggrepel::geom_text_repel(box.padding=0.6, 
                           aes(label=type), data=systems_merged[which(systems_merged$prop.Refseq>1),], max.overlaps = Inf)

# This is contig *not* genome
complete_systems$contig = sub("(^[^_]+_[^_]+)_.*", "\\1", complete_systems$sys_id)
atb_systems$contig = sub("(^[^_]+_[^_]+)_.*", "\\1", atb_systems$sys_id)

# Number of systems per genome
# ATB: 7.05
nrow(atb_systems)/644699
# RefSeq: 7.91
nrow(complete_systems)/1672